### ISSUE TITLE
GraphView Title?

### ISSUE THREAD

**Issue by MacKaSL** [philackm/ScrollableGraphView#100]
Is it possible to set a title for the graph view?

**Comment by iKisliy** [comment]
Easiest way — add subview 🤷🏼‍♂️

**Comment by MacKaSL** [comment]
yeah.. but i was hoping you could add inspectable attribute for the title to just make it much more easier. but a workaround is to add a subview also works. Thanks.

**Comment by philackm** [comment]
I prefer to leave this to the user. No title I add will satisfy all designs (location, styling, etc). The user can add their own views wherever they please :)
