### ISSUE TITLE
Fill Starting at 0 with Reference Lines

### ISSUE THREAD

**Issue by hsandhu** [philackm/ScrollableGraphView#102]
After enabling reference lines, the x-axis labels are 'filled' (see attachement). 

Is it possible to shift the fill up to zero? 
![screen shot 2017-09-05 at 11 44 26 pm](https://user-images.githubusercontent.com/122918/30097794-33511ff6-9294-11e7-8d14-0a99d3ed9050.png)

**Comment by philackm** [comment]
Moving to #134
