### ISSUE TITLE
numberOfPoints

### ISSUE THREAD

**Issue by Neilfau** [philackm/ScrollableGraphView#103]
Hi,

Is it possible to have a different number of points per plot? I noticed in the documentation you show this function:

`numberOfPoints(forPlot plot: Plot) -> Int`

Yet the protocol will only let me use this:

`numberOfPoints() -> Int`

Has this function been removed?

Thanks,

Neil

**Comment by iKisliy** [comment]
Due to ScrollableGraphViewDataSource it's only non-argument function with comment 
`// This now forces the same number of points in each plot.`
Personally I suggest use separate models for plots
