### ISSUE TITLE
Reload data crash

### ISSUE THREAD

**Issue by MacKaSL** [philackm/ScrollableGraphView#105]
when new data is added to the array and reload the graph view, it crashes "index out of bound exception". I update the array before calling reload method. And also i did debug this, `numberOfPoints` returns correct value and seems like `value(forPlot plot: Plot, atIndex pointIndex: Int) -> Double` is not getting updated?

**Comment by RiuHDuo** [comment]
```
    // Limitation: Can only be used when reloading the same number of data points!
    public func reload() {
        stopAnimations()
        let numbuer = dataSource!.numberOfPoints()
        for plot in self.plots {
            if plot.graphPoints.count != numbuer {
                plot.createPlotPoints(numberOfPoints: dataSource!.numberOfPoints(), range: range)
            }
        }
        rangeDidChange()
        updateUI()
        updatePaths()
        updateLabelsForCurrentInterval()
    }
```

i think we need re-write reload fuction

**Comment by MacKaSL** [comment]
I'm using this library in my ongoing project but I'm stuck that I can't release this on AppStore due to this crash. Please I hope you will be able to solve this. Thanks for the response.. :)

**Comment by philackm** [comment]
This is not supported. Feel free to implement it and submit a pull request.

**Comment by ahmedAlmasri** [comment]
+1

**Comment by chyiiiiiiiiiiii** [comment]
I can solve this problem .
Just have this codes after you get data

> graphView.dataSource = self
> graphView.reload()

Warning : Don't set **dataSource** at the beginning

I hope it can works for you
