### ISSUE TITLE
Support for Swift 4 

### ISSUE THREAD

**Issue by SergioKoko** [philackm/ScrollableGraphView#108]
Hi everyone.
I install xcode 9 and a lot of errors are showing. Is there any update for swift 4?

Thank you
Regards

**Comment by barnaclejive** [comment]
I've submitted a PR. The changes are pretty minor. I've forked it for myself and will point my podfile at my repo until @philackm does an official update.

pod 'ScrollableGraphView', :git => 'https://github.com/barnaclejive/ScrollableGraphView', :branch => 'master'

**Comment by timusus** [comment]
Can be closed thanks to #118

**Comment by philackm** [comment]
Has been implemented.
