### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by ricburton** [philackm/ScrollableGraphView#11]
We’d love to use this library in our Mac app—it looks fantastic!

**Comment by jdfweb** [comment]
+1 on this!

**Comment by cliftonlabrum** [comment]
I would love this in my Mac app. Anyone get it working yet?

**Comment by cliftonlabrum** [comment]
I've tried converting this to macOS, but I haven't gotten too far. I started by converting all instance of `UI***` to `NS***` but I still have 40 build errors. :) 

Anyone having better luck or find something you like better?

**Comment by philackm** [comment]
Closing as will not implement in forseeable future.
