### ISSUE TITLE
y-axis displaying repeated values

### ISSUE THREAD

**Issue by frelei** [philackm/ScrollableGraphView#119]
I am trying to plot those points: [2.19325733184814, 0.883669853210449, 0.83063006401062, 0.787178874015808, 0.774782657623291]  and I am getting the result below. The y-axis repeat the values and I am using set the variable shouldAdaptRange to true. Is there a way to make the y-axis display a better range? 

<img width="375" alt="screen shot 2017-12-14 at 13 47 35" src="https://user-images.githubusercontent.com/2272745/34000852-970e723e-e0d5-11e7-8bfb-a8c2314d0430.png">

Thanks

**Comment by philackm** [comment]
This can be solved by setting `referenceLineNumberOfDecimalPlaces` on the `ReferenceLines`.
