### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [philackm/ScrollableGraphView#12]
Hi,
For iOS and OS X projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by philackm** [comment]
This should be fine. I'll take a look at it next chance I get.

**Comment by EternalBlack** [comment]
+1
Carthage would be really usefull, otherwise I unfortunately wont be able to use it because of my teams policy :(

**Comment by philackm** [comment]
This has been added in version 4. 👍
