### ISSUE TITLE
How to add only reference line for showing a limit?

### ISSUE THREAD

**Issue by MHX792** [philackm/ScrollableGraphView#121]
How to accomplish something like this where the refence line shows a limit:

![screen shot 2017-12-24 at 13 47 48](https://user-images.githubusercontent.com/12123471/34326582-0e46064a-e8b1-11e7-8ae1-bd262ffa775f.png)

**Comment by philackm** [comment]
This is not implemented in the current version. However it seems like a really good feature and if anyone is willing, I'm happy to review and merge pull requests.

**Comment by weiran** [comment]
You can achieve something like this already by adding another reference line with an absolute position.
