### ISSUE TITLE
Multiple charts in same collection view copy each other's data

### ISSUE THREAD

**Issue by mrh-is** [philackm/ScrollableGraphView#123]
I am trying to embed a small graph in a`UICollectionViewCell`. If there's only one cell, everything works great. 👍

But if I have multiple cells, the graphs somehow seem to share data. 🤔 When I call `set(data:withLabels:)` on each of them (I'm still using v3.1.0, maybe this is fixed by v4?), any individual graph may use any data set. For example, two graphs could both have the first data set, or both the second data set, or each the correct data set (I haven't seen them swap data). I've been trying to figure out how this is possible, but I don't see anything that could cause this.

Has any one seen this (or fixed it)? I will check out the latest library version to see if that fixes it.

**Comment by mrh-is** [comment]
Debugging update: This appears to be related to the collection view's cell dequeueing. In my test case, I have two cells with graphs, which are assigned to different index paths at different times (while my data is downloading and updating the model). The rest of the cells' subview appear to be unaffected by this issue.

Maybe something about the way the graphs are drawing? `CADisplayLink` maybe? (I don't know ton about the way that works.)

**Comment by philackm** [comment]
I haven't been able to reproduce this using V4. If anyone can recreate this, please upload a small project with it occurring and we can debug further.
