### ISSUE TITLE
Index out of range error 

### ISSUE THREAD

**Issue by imburakoner** [philackm/ScrollableGraphView#124]
I'm getting index out of range error  at setPlotPointPositions function . That error only occure at iphone 5s. Dou you have any idea. How can i fix that

**Comment by woaibujian** [comment]
Same issue here.

**Comment by philackm** [comment]
Sorry for the late reply, if either of you are still around (or care), I'll take a look at this on the 5s simulator. What version of iOS was this for?

**Comment by beraybentesen** [comment]
Problem occur when I use reload method after adding new items into data source.

**Comment by philackm** [comment]
Currently reloading the graph with a different number of points will cause the graph to error. Investigating this in #136
