### ISSUE TITLE
Dynamically Adding New Values

### ISSUE THREAD

**Issue by johnallen24** [philackm/ScrollableGraphView#131]
Hey 
Is it possible to dynamically add new values to the graph and have the graph scroll along as the values are added?

**Comment by philackm** [comment]
Whilst this would be a good feature, it is currently not supported. Sorry!

**Comment by beraybentesen** [comment]
I believe that this would be the most significant feature, any estimated date for that ?

**Comment by philackm** [comment]
@beraybentesen It would definitely be great to have. However I have a feeling it will be quite complex and difficult to implement. I'm going to investigate the possibility of adding this feature, you can keep track of the progress here: #136 

However, I can only work in this when I have free time between work and study, I don't have any good estimates as to when it would be implemented.
