### ISSUE TITLE
DotPlot are not clickable

### ISSUE THREAD

**Issue by Rakibrz** [philackm/ScrollableGraphView#170]
How can I achieve dot plots clickable? I want to fire the event on the selected plot.

**Comment by trevorphillipscoding** [comment]
any update on this?

**Comment by sanctovali** [comment]
> How can I achieve dot plots clickable? I want to fire the event on the selected plot.

I can suggest you to invert the calculatePosition(atIndex: , value:) -> CGpoint to get index, and then handle this

**Comment by jpnoe** [comment]
> > How can I achieve dot plots clickable? I want to fire the event on the selected plot.
> 
> I can suggest you to invert the calculatePosition(atIndex: , value:) -> CGpoint to get index, and then handle this

How do you mean?
