### ISSUE TITLE
Multi Line Graph and an option to select the node

### ISSUE THREAD

**Issue by kanishkatn** [philackm/ScrollableGraphView#41]
Hi,

Could you please add an option to plot multiple values on the graph and an option to select a node/value?

Thanks. Love the Graph.

**Comment by gangbusters** [comment]
I also +1 multiple values on a graph.  Let us know if you're working on it and/or need help with it @philackm!

**Comment by Punith1234** [comment]
@philackm it would be great if we can have a multi line option

**Comment by jamesktan** [comment]
One workaround that I've used here is to overlay 2 Scrollable Graph Views at the same position and then use the UIScrollViewDelegate method to scroll each plot (using the offset) like below:

 ```
 func scrollViewDidScroll(_ scrollView: UIScrollView) {
    if scrollView == graphView2 || scrollView == graphView {
      let offset = scrollView.contentOffset
      graphView?.contentOffset = offset
      graphView2?.contentOffset = offset
    }
  }
```

**Comment by Punith1234** [comment]
@jamesktan  hey, Is't possible for you to share some more information or code on how were you able to solve this.. This will be very helpful for us

**Comment by jamesktan** [comment]
@Punith1234 Sure, but there's not much more to it other than:

```
        graphView?.delegate = self
        graphView2?.delegate = self
        self.plotView.insertSubview(graphView2!, aboveSubview: graphView!)
```

Everything else is really just:
- Create a container view (plotView in the above)
- Create a graph and add it to the container
- Create the second graph, make the background transparent, set the axis and all to match the first graph
- Add the second graph above the first graph

**Comment by Punith1234** [comment]
@jamesktan  thanks a lot ..

**Comment by philackm** [comment]
The multiple line section of this issue has been added in version 4. I will create a new issue for the touchability.
