### ISSUE TITLE
How do I disable vertical scrolling on the graph?

### ISSUE THREAD

**Issue by kanishkatn** [philackm/ScrollableGraphView#42]
I wanna keep just the horizontal scrolling and disable vertical. How do I do this?

This is the default behavior
![screen shot 2016-08-18 at 7 20 48 pm](https://cloud.githubusercontent.com/assets/4919645/17776182/06ec5f3c-6579-11e6-95cb-6664dbf2309a.png)

I want the graph t position itself like this. 

![screen shot 2016-08-18 at 7 21 10 pm](https://cloud.githubusercontent.com/assets/4919645/17776210/22dc46ee-6579-11e6-861b-4cef7aaf5307.png)

Or even disable the vertical scroll. Please help me.

**Comment by philackm** [comment]
There shouldn't be any vertical scrolling, you should be able to utilise the margins to achieve what you want.

**Comment by kanishkatn** [comment]
There was vertical scrolling in the container scrollview. I somehow disabled it. Please close the issue. 

Thanks.
