### ISSUE TITLE
Can we use more than one lines?

### ISSUE THREAD

**Issue by praveenbroski** [philackm/ScrollableGraphView#62]
I want to show more than one lines in the graph. Is it possible to show add two or more lines in the same graph? Please provide a solution.

**Comment by gkaimakas** [comment]
"Please provide the solution ASAP." seems quite rude.

**Comment by praveenbroski** [comment]
@gkaimakas does please means "Rude"? Removed it.

**Comment by sleepwalkerfx** [comment]
Is it possible to add more than one line at all, with this current version?

**Comment by philackm** [comment]
This was added in version 4. 👍
