### ISSUE TITLE
Use labels in data points

### ISSUE THREAD

**Issue by GabrielBor** [philackm/ScrollableGraphView#64]
I would like to put each label inside the points, but I'm having a bit of difficulty

**Comment by philackm** [comment]
I'm not sure what you mean by "inside the points", do you mean something like #63?

**Comment by GabrielBor** [comment]
Thanks :D Helped me a lot thanks :D

**Comment by abara-kedavra** [comment]
Is it possible to make label Integer, without ".0"? For example "10" instead of "10.0"

**Comment by MHX792** [comment]
@philackm is this really implemented in version 4? I just downloaded the demo project and in `createBarGraph` I added `referenceLines.shouldShowLabels = true` which unfortunately did nothing.
