### ISSUE TITLE
Bars above the reference lines 

### ISSUE THREAD

**Issue by abara-kedavra** [philackm/ScrollableGraphView#70]
Is it possible to make bars not under, but above the reference lines? What should I change?

**Comment by abara-kedavra** [comment]
Should I implement something here? 

@objc public enum ScrollableGraphViewReferenceLineType : Int {
    case cover
    //case Edge // FUTURE: Implement
}

**Comment by philackm** [comment]
For future reference if anyone else is having the same query, you would have to change the order of the `drawingView` and the `referenceLineView`. If this was attached to some boolean `referenceLinesBelowPlots` and adjusted accordingly, could be a good pull request.
