### ISSUE TITLE
How do I add one more line to the same graph? 

### ISSUE THREAD

**Issue by hkapplet1** [philackm/ScrollableGraphView#71]
How do I add one more line to the same graph? 

I have added a new data set data2 and add this to the graph after data1 was set, but it fails.

`let data2: [Double] = [4, 8, 15, 16, 23, 42, 8, 15, 16, 23, 23, 42]`

`graphView.set(data: data1, withLabels: labels)`
`graphView.set(data: data2, withLabels: labels2)`

The last set of data (i.e. data2) is only available.

Do you have any suggestion or any other method to do? Thanks a lot!

**Comment by ShvetsJr** [comment]
Please read other issues before open new one! Its not currently supported https://github.com/philackm/Scrollable-GraphView/issues/41.

**Comment by philackm** [comment]
This was added in version 4 👍
