### ISSUE TITLE
How to detect dot click from line graph and  bar click from bar graph?

### ISSUE THREAD

**Issue by smitaAcellere** [philackm/ScrollableGraphView#72]

**Comment by smitaAcellere** [comment]
![screen shot 2017-03-07 at 12 05 14 pm](https://cloud.githubusercontent.com/assets/17287041/23644695/82fa3e16-032e-11e7-9ecf-d326b80ba7fe.png)
![screen shot 2017-03-07 at 12 05 52 pm](https://cloud.githubusercontent.com/assets/17287041/23644696/8357c680-032e-11e7-8cde-ddaa57f4d6d3.png)

I want to show labels like this designs

**Comment by ShvetsJr** [comment]
Check this one https://github.com/philackm/Scrollable-GraphView/pull/69. After you change your code to this you can add you own custom views on dot click position.

**Comment by mithunmathew1990** [comment]
@smitaAcellere  checkout  #82

**Comment by philackm** [comment]
Consolidating to #133
