### ISSUE TITLE
fatal error: Index out of range after Rotate the Device

### ISSUE THREAD

**Issue by JeanetteMueller** [philackm/ScrollableGraphView#79]
Crash in Line 857:
            `let firstDataPoint = graphPoints[activePointsInterval.lowerBound]`

**Comment by manuel21** [comment]
Do you already know how to fix it?

`  // left point only
            let leftPoint = graphPoints[leftDataPointIndex].location  //EXC_BAD_INSTRUCTION
            
            if shouldDrawBarLayer {
                let barWidthToRightOfX = locationOfTouchPoint.x + (barWidth / 2)
                if locationOfTouchPoint.y < leftPoint.y &&
                    barWidthToRightOfX > locationOfTouchPoint.x {
                    triggerDelegateWith(index: leftDataPointIndex)
                }
`

**Comment by philackm** [comment]
Should be fixed, can't replicate in version 4 when rotating the device. If this still occurs please reopen.
