### ISSUE TITLE
How to update the graph several times in the same screen?

### ISSUE THREAD

**Issue by manuel21** [philackm/ScrollableGraphView#80]
How to update the graph with differents datasource.

For example:
The first time I received 3 points to draw, then in the same screen I tap a button to request again but now I received 10 points to draw.

how is possible in the same screen reload the graph data?

**Comment by NunoAlexandre** [comment]
Hi @manuel21,

I'm attempting to do the same. Not sure how you moved on, but I did this:

``
 self.chartView.subviews.forEach{$0.setNeedsDisplay()}
 self.chartView.addSubview(graph)
``

where `chartView` is a container view where the `graph` (ScrollableGraphView) is under.

**Comment by manuel21** [comment]
Hi @NunoAlexandre thank you very much. It Works!

**Comment by NunoAlexandre** [comment]
Cool, @manuel21! Note that you can also just do:

```
graph.removeFromSuperview()
 self.chartView.addSubview(graph)
```

It depends on your context and what better fits your needs. Cheers!

**Comment by philackm** [comment]
Version 4 now supports reloading data, but not reloading with a different amount of data points. Once the number of points for the graph is set it cannot be changed. (That will hopefully be coming in the future.)

**Comment by sandeepwalia95** [comment]
Where did you guys call these? I keep crashing due to the number of data points increasing. Any help is very much appreciated thanks.
