### ISSUE TITLE
Update dynamically fails. Graph fails to load with updated values.. 

### ISSUE THREAD

**Issue by hemanthalluri** [philackm/ScrollableGraphView#83]
@IBOutlet var sc : ScrollableGraphView!
    
    var metaData : [Double] = []
    var metaString : [String] = []
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let socket = SocketIOClient(socketURL: URL(string: "http://ios-test.us-east-1.elasticbeanstalk.com")!, config: [.log(true), .forcePolling(true), .nsp("/random")])
        
        
        socket.on("capture") {data, ack in
            for items in data
            {
                let receivedData  = items as! Double
                let timeDate = DateFormatter.localizedString(from: Date(), dateStyle: .none, timeStyle: .medium)
                let filterData : Double = receivedData
                if (filterData  <= 9 && filterData >= 1)
                {
                    //self.sc.rangeMax = 10
                    let displayDate = "\(filterData) at \(timeDate)"
                    print("============================")
                    print(displayDate)
                    print("============================")
                    self.metaData.append(filterData)
                    self.metaString.append(timeDate)

                }
                self.sc.set(data: self.metaData, withLabels: self.metaString)

            }
            
        }

**Comment by philackm** [comment]
This should now be possible with the new API for version 4. Use the `ScrollableGraphViewDataSource` and the `reload` method. This will work as long as you are reloading data for the same number of points.
