### ISSUE TITLE
How to make graph auto move to end point 

### ISSUE THREAD

**Issue by hemanthalluri** [philackm/ScrollableGraphView#85]
How to make graph move  dynamically like health app graph.. ?

**Comment by philackm** [comment]
I'm not too familiar with the health app, however there are two options of moving the graph to the end point.

1) You can start all the way to the right side of the graph (the last point) by setting the `ScrollablegraphView.direction` property on the graph.

2) `ScrollableGraphView` is a subclass of `UIScrollView`, any method of moving a `UIScrollView` should also work on the `ScrollableGraphView`.
