### ISSUE TITLE
label on x axis is not updating

### ISSUE THREAD

**Issue by iOS67** [philackm/ScrollableGraphView#87]

**Comment by iOS67** [comment]
reference label is not changing while i updating the graph

**Comment by philackm** [comment]
I'll take a look now.

**Comment by philackm** [comment]
I've found the problem, I'll work on a fix for it now.

**Comment by philackm** [comment]
Fixed! If you're using CocoaPods or Carthage, try using version 4.0.4.

**Comment by iOS67** [comment]
great 👍
