### ISSUE TITLE
Support for Objective-C

### ISSUE THREAD

**Issue by jlubeck** [philackm/ScrollableGraphView#89]
Hi! This looks like a great library! I was wondering if it can be used within an Objective-C project? 
I tried importing it via CocoaPods, but although I can create a ScrollableGraphView, I can´t seem to create a LinePlot, so I can´t finish the setup. 

Any ideas?

Thanks!

**Comment by davidhodge** [comment]
It can be done. How'd you set up the view?

**Comment by jlubeck** [comment]
I did this: 	self.graphView = [[ScrollableGraphView alloc] initWithFrame:self.viewChart.frame];

Which another problema is that the dataSource seems to get lost on the ObjectiveC initializer...

**Comment by davidhodge** [comment]
Perhaps that's the issue. Are you expecting this to have a data source / delegate pattern? It's been a while since I've updated (so I haven't looked at the latest code), but when I did it I don't believe there was a data source kind of pattern. I set graph values with setData:withLabels:, for example.

Obviously, would be helpful to know what other setup you do. Maybe more code context would help. Like are you setting any other params? Are you adding it as a subview to something to get it onto the screen.

**Comment by philackm** [comment]
Hmm. The delegate/data source pattern is available in version 4 and higher. Have you specified version 4.0.4 in your podfile? I'll try it out in an objective c program this evening and get back to you with whether or not I'm experiencing the same thing.

**Comment by davidhodge** [comment]
That makes sense. I moved away from using Cocoapods for this because I had to make some hacky changes.

**Comment by jlubeck** [comment]
Hey guys, thanks for the quick input. Like I mentioned originally, creating the ScrollableGraphView object itself doesn't seem to be the main issue. The problem is that I can´t seem to create a PlotLine. I get error that the class doesn't exist. Seems like those files are not being generated on the Bridge file or something...

@philackm I did specify version 4.0.4. Had to do it per the commit hash, as Cocopoads doesn´t seem to have the latest version yet.

**Comment by jlubeck** [comment]
A very stripped down example on how to initialize everything in ObjC would be awesome!

**Comment by philackm** [comment]
Okay so I had a look, I had not added the `@objc` tags on the `Plot` classes and the `ScrollableGraphViewDataSource` protocol as I was testing solely in Swift. If you take a look at the `objc` branch, you will see a version that includes them and the graph loads properly in objective c projects.

![screen shot 2017-07-11 at 5 59 25 pm](https://user-images.githubusercontent.com/2552214/28057496-b84b2b6e-6663-11e7-979c-8b98b700fe69.png)

However you can see in the [ViewController.m](https://github.com/philackm/ScrollableGraphView/blob/6c5244e13cd90968fa9f5a929fd110a5e5e330d6/graphview_example_objc/GraphObjC/ViewController.m) that there are some issues with the API. Things like `addPlotWithPlot` which I will have to fix before updating CocoaPods.
