### ISSUE TITLE
Multi line graph

### ISSUE THREAD

**Issue by elavarasanFluke** [philackm/ScrollableGraphView#9]
is it possible to show multiple line in the graph?

**Comment by philackm** [comment]
This is currently not available, however it is on my TODO list and will be available in the future.

**Comment by guydaher** [comment]
+1, would really like to have that!

**Comment by 36bydesign** [comment]
Any progress on this? Love this lib

**Comment by kanishkatn** [comment]
Please do it soon

**Comment by dipen0807** [comment]
Loved your work,requesting you to provide multi line graph. Please please, do it soon.

**Comment by eliasturbay** [comment]
+1 it would be great if you add multi-line support

**Comment by jkritikos** [comment]
+1 for me too!

**Comment by philackm** [comment]
This has been added in version 4. 👍
